# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: queue.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\x12\x04mpmq\".\n\x0eProduceRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1e\n\x0cProduceReply\x12\x0e\n\x06offset\x18\x01 \x01(\x03\"C\n\x0e\x43onsumeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\r\n\x05group\x18\x02 \x01(\t\x12\x13\n\x0bmax_records\x18\x03 \x01(\x05\"3\n\x06Record\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\n\n\x02ts\x18\x02 \x01(\x03\x12\r\n\x05value\x18\x03 \x01(\x0c\"-\n\x0c\x43onsumeReply\x12\x1d\n\x07records\x18\x01 \x03(\x0b\x32\x0c.mpmq.Record2x\n\x0cQueueService\x12\x33\n\x07Produce\x12\x14.mpmq.ProduceRequest\x1a\x12.mpmq.ProduceReply\x12\x33\n\x07\x43onsume\x12\x14.mpmq.ConsumeRequest\x1a\x12.mpmq.ConsumeReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCEREQUEST']._serialized_start=21
  _globals['_PRODUCEREQUEST']._serialized_end=67
  _globals['_PRODUCEREPLY']._serialized_start=69
  _globals['_PRODUCEREPLY']._serialized_end=99
  _globals['_CONSUMEREQUEST']._serialized_start=101
  _globals['_CONSUMEREQUEST']._serialized_end=168
  _globals['_RECORD']._serialized_start=170
  _globals['_RECORD']._serialized_end=221
  _globals['_CONSUMEREPLY']._serialized_start=223
  _globals['_CONSUMEREPLY']._serialized_end=268
  _globals['_QUEUESERVICE']._serialized_start=270
  _globals['_QUEUESERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
